// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_assist.proto

package org.github.omnbmh.samples.grpc.protobuf.work.assist;

public interface TextResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.work.assist.TextResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string encryptText = 2;</code>
   */
  String getEncryptText();
  /**
   * <code>string encryptText = 2;</code>
   */
  com.google.protobuf.ByteString
      getEncryptTextBytes();

  /**
   * <code>string decryptText = 3;</code>
   */
  String getDecryptText();
  /**
   * <code>string decryptText = 3;</code>
   */
  com.google.protobuf.ByteString
      getDecryptTextBytes();
}
