// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_assist.proto

package org.github.omnbmh.samples.grpc.protobuf.work.assist;

public final class WorkAssistProto {
  private WorkAssistProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_work_assist_TextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_work_assist_TextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_work_assist_TextResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_work_assist_TextResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021work_assist.proto\022\024protobuf.work.assis" +
      "t\"(\n\013TextRequest\022\014\n\004text\030\001 \001(\t\022\013\n\003key\030\002 " +
      "\001(\t\"F\n\014TextResponse\022\014\n\004text\030\001 \001(\t\022\023\n\013enc" +
      "ryptText\030\002 \001(\t\022\023\n\013decryptText\030\003 \001(\t2\273\001\n\t" +
      "TextCodec\022V\n\013encryptText\022!.protobuf.work" +
      ".assist.TextRequest\032\".protobuf.work.assi" +
      "st.TextResponse\"\000\022V\n\013decryptText\022!.proto" +
      "buf.work.assist.TextRequest\032\".protobuf.w" +
      "ork.assist.TextResponse\"\000BH\n3org.github." +
      "omnbmh.samples.grpc.protobuf.work.assist",
      "B\017WorkAssistProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_work_assist_TextRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_work_assist_TextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_work_assist_TextRequest_descriptor,
        new String[] { "Text", "Key", });
    internal_static_protobuf_work_assist_TextResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_work_assist_TextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_work_assist_TextResponse_descriptor,
        new String[] { "Text", "EncryptText", "DecryptText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
