// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdbdata.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface DruidResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DruidResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>string exetime = 2;</code>
   */
  java.lang.String getExetime();
  /**
   * <code>string exetime = 2;</code>
   */
  com.google.protobuf.ByteString
      getExetimeBytes();

  /**
   * <code>string servertimestamp = 3;</code>
   */
  java.lang.String getServertimestamp();
  /**
   * <code>string servertimestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getServertimestampBytes();
}
