// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqljdbc.proto

package org.github.omnbmh.samples.grpc.protobuf;

/**
 * Protobuf type {@code JdbcResponse1}
 */
public  final class JdbcResponse1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JdbcResponse1)
    JdbcResponse1OrBuilder {
  // Use JdbcResponse1.newBuilder() to construct.
  private JdbcResponse1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JdbcResponse1() {
    jdbcurl_ = "";
    username_ = "";
    userpassword_ = "";
    driverclassname_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JdbcResponse1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            jdbcurl_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            userpassword_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            driverclassname_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.github.omnbmh.samples.grpc.protobuf.Mysqljdbc.internal_static_JdbcResponse1_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.github.omnbmh.samples.grpc.protobuf.Mysqljdbc.internal_static_JdbcResponse1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.class, org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.Builder.class);
  }

  public static final int JDBCURL_FIELD_NUMBER = 1;
  private volatile java.lang.Object jdbcurl_;
  /**
   * <code>string jdbcurl = 1;</code>
   */
  public java.lang.String getJdbcurl() {
    java.lang.Object ref = jdbcurl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jdbcurl_ = s;
      return s;
    }
  }
  /**
   * <code>string jdbcurl = 1;</code>
   */
  public com.google.protobuf.ByteString
      getJdbcurlBytes() {
    java.lang.Object ref = jdbcurl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jdbcurl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 2;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERPASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object userpassword_;
  /**
   * <code>string userpassword = 3;</code>
   */
  public java.lang.String getUserpassword() {
    java.lang.Object ref = userpassword_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userpassword_ = s;
      return s;
    }
  }
  /**
   * <code>string userpassword = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserpasswordBytes() {
    java.lang.Object ref = userpassword_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userpassword_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRIVERCLASSNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object driverclassname_;
  /**
   * <code>string driverclassname = 4;</code>
   */
  public java.lang.String getDriverclassname() {
    java.lang.Object ref = driverclassname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      driverclassname_ = s;
      return s;
    }
  }
  /**
   * <code>string driverclassname = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDriverclassnameBytes() {
    java.lang.Object ref = driverclassname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      driverclassname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getJdbcurlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jdbcurl_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!getUserpasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userpassword_);
    }
    if (!getDriverclassnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, driverclassname_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getJdbcurlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jdbcurl_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!getUserpasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userpassword_);
    }
    if (!getDriverclassnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, driverclassname_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1)) {
      return super.equals(obj);
    }
    org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 other = (org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1) obj;

    boolean result = true;
    result = result && getJdbcurl()
        .equals(other.getJdbcurl());
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && getUserpassword()
        .equals(other.getUserpassword());
    result = result && getDriverclassname()
        .equals(other.getDriverclassname());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JDBCURL_FIELD_NUMBER;
    hash = (53 * hash) + getJdbcurl().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + USERPASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getUserpassword().hashCode();
    hash = (37 * hash) + DRIVERCLASSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDriverclassname().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JdbcResponse1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JdbcResponse1)
      org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.omnbmh.samples.grpc.protobuf.Mysqljdbc.internal_static_JdbcResponse1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.omnbmh.samples.grpc.protobuf.Mysqljdbc.internal_static_JdbcResponse1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.class, org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.Builder.class);
    }

    // Construct using org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      jdbcurl_ = "";

      username_ = "";

      userpassword_ = "";

      driverclassname_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.github.omnbmh.samples.grpc.protobuf.Mysqljdbc.internal_static_JdbcResponse1_descriptor;
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 getDefaultInstanceForType() {
      return org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.getDefaultInstance();
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 build() {
      org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 buildPartial() {
      org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 result = new org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1(this);
      result.jdbcurl_ = jdbcurl_;
      result.username_ = username_;
      result.userpassword_ = userpassword_;
      result.driverclassname_ = driverclassname_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1) {
        return mergeFrom((org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 other) {
      if (other == org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1.getDefaultInstance()) return this;
      if (!other.getJdbcurl().isEmpty()) {
        jdbcurl_ = other.jdbcurl_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getUserpassword().isEmpty()) {
        userpassword_ = other.userpassword_;
        onChanged();
      }
      if (!other.getDriverclassname().isEmpty()) {
        driverclassname_ = other.driverclassname_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object jdbcurl_ = "";
    /**
     * <code>string jdbcurl = 1;</code>
     */
    public java.lang.String getJdbcurl() {
      java.lang.Object ref = jdbcurl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jdbcurl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jdbcurl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJdbcurlBytes() {
      java.lang.Object ref = jdbcurl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jdbcurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jdbcurl = 1;</code>
     */
    public Builder setJdbcurl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jdbcurl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jdbcurl = 1;</code>
     */
    public Builder clearJdbcurl() {
      
      jdbcurl_ = getDefaultInstance().getJdbcurl();
      onChanged();
      return this;
    }
    /**
     * <code>string jdbcurl = 1;</code>
     */
    public Builder setJdbcurlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jdbcurl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userpassword_ = "";
    /**
     * <code>string userpassword = 3;</code>
     */
    public java.lang.String getUserpassword() {
      java.lang.Object ref = userpassword_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userpassword_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userpassword = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserpasswordBytes() {
      java.lang.Object ref = userpassword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userpassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userpassword = 3;</code>
     */
    public Builder setUserpassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userpassword_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userpassword = 3;</code>
     */
    public Builder clearUserpassword() {
      
      userpassword_ = getDefaultInstance().getUserpassword();
      onChanged();
      return this;
    }
    /**
     * <code>string userpassword = 3;</code>
     */
    public Builder setUserpasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userpassword_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object driverclassname_ = "";
    /**
     * <code>string driverclassname = 4;</code>
     */
    public java.lang.String getDriverclassname() {
      java.lang.Object ref = driverclassname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        driverclassname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string driverclassname = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDriverclassnameBytes() {
      java.lang.Object ref = driverclassname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        driverclassname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string driverclassname = 4;</code>
     */
    public Builder setDriverclassname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      driverclassname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string driverclassname = 4;</code>
     */
    public Builder clearDriverclassname() {
      
      driverclassname_ = getDefaultInstance().getDriverclassname();
      onChanged();
      return this;
    }
    /**
     * <code>string driverclassname = 4;</code>
     */
    public Builder setDriverclassnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      driverclassname_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:JdbcResponse1)
  }

  // @@protoc_insertion_point(class_scope:JdbcResponse1)
  private static final org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1();
  }

  public static org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JdbcResponse1>
      PARSER = new com.google.protobuf.AbstractParser<JdbcResponse1>() {
    public JdbcResponse1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JdbcResponse1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JdbcResponse1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JdbcResponse1> getParserForType() {
    return PARSER;
  }

  public org.github.omnbmh.samples.grpc.protobuf.JdbcResponse1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

