// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqljdbc.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface JdbcResponse1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:JdbcResponse1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jdbcurl = 1;</code>
   */
  java.lang.String getJdbcurl();
  /**
   * <code>string jdbcurl = 1;</code>
   */
  com.google.protobuf.ByteString
      getJdbcurlBytes();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string userpassword = 3;</code>
   */
  java.lang.String getUserpassword();
  /**
   * <code>string userpassword = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserpasswordBytes();

  /**
   * <code>string driverclassname = 4;</code>
   */
  java.lang.String getDriverclassname();
  /**
   * <code>string driverclassname = 4;</code>
   */
  com.google.protobuf.ByteString
      getDriverclassnameBytes();
}
