// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdbdata.proto

package org.github.omnbmh.samples.grpc.protobuf;

/**
 * Protobuf type {@code JdbcRequest}
 */
public  final class JdbcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JdbcRequest)
    JdbcRequestOrBuilder {
  // Use JdbcRequest.newBuilder() to construct.
  private JdbcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JdbcRequest() {
    datasourcename_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JdbcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            datasourcename_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.github.omnbmh.samples.grpc.protobuf.Searchdbdata.internal_static_JdbcRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.github.omnbmh.samples.grpc.protobuf.Searchdbdata.internal_static_JdbcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.class, org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.Builder.class);
  }

  public static final int DATASOURCENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object datasourcename_;
  /**
   * <code>string datasourcename = 1;</code>
   */
  public java.lang.String getDatasourcename() {
    java.lang.Object ref = datasourcename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datasourcename_ = s;
      return s;
    }
  }
  /**
   * <code>string datasourcename = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDatasourcenameBytes() {
    java.lang.Object ref = datasourcename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datasourcename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDatasourcenameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datasourcename_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDatasourcenameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, datasourcename_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.github.omnbmh.samples.grpc.protobuf.JdbcRequest)) {
      return super.equals(obj);
    }
    org.github.omnbmh.samples.grpc.protobuf.JdbcRequest other = (org.github.omnbmh.samples.grpc.protobuf.JdbcRequest) obj;

    boolean result = true;
    result = result && getDatasourcename()
        .equals(other.getDatasourcename());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASOURCENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDatasourcename().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.github.omnbmh.samples.grpc.protobuf.JdbcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JdbcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JdbcRequest)
      org.github.omnbmh.samples.grpc.protobuf.JdbcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.omnbmh.samples.grpc.protobuf.Searchdbdata.internal_static_JdbcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.omnbmh.samples.grpc.protobuf.Searchdbdata.internal_static_JdbcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.class, org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.Builder.class);
    }

    // Construct using org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      datasourcename_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.github.omnbmh.samples.grpc.protobuf.Searchdbdata.internal_static_JdbcRequest_descriptor;
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcRequest getDefaultInstanceForType() {
      return org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.getDefaultInstance();
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcRequest build() {
      org.github.omnbmh.samples.grpc.protobuf.JdbcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.github.omnbmh.samples.grpc.protobuf.JdbcRequest buildPartial() {
      org.github.omnbmh.samples.grpc.protobuf.JdbcRequest result = new org.github.omnbmh.samples.grpc.protobuf.JdbcRequest(this);
      result.datasourcename_ = datasourcename_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.github.omnbmh.samples.grpc.protobuf.JdbcRequest) {
        return mergeFrom((org.github.omnbmh.samples.grpc.protobuf.JdbcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.github.omnbmh.samples.grpc.protobuf.JdbcRequest other) {
      if (other == org.github.omnbmh.samples.grpc.protobuf.JdbcRequest.getDefaultInstance()) return this;
      if (!other.getDatasourcename().isEmpty()) {
        datasourcename_ = other.datasourcename_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.github.omnbmh.samples.grpc.protobuf.JdbcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.github.omnbmh.samples.grpc.protobuf.JdbcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object datasourcename_ = "";
    /**
     * <code>string datasourcename = 1;</code>
     */
    public java.lang.String getDatasourcename() {
      java.lang.Object ref = datasourcename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datasourcename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string datasourcename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatasourcenameBytes() {
      java.lang.Object ref = datasourcename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datasourcename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string datasourcename = 1;</code>
     */
    public Builder setDatasourcename(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datasourcename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string datasourcename = 1;</code>
     */
    public Builder clearDatasourcename() {
      
      datasourcename_ = getDefaultInstance().getDatasourcename();
      onChanged();
      return this;
    }
    /**
     * <code>string datasourcename = 1;</code>
     */
    public Builder setDatasourcenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datasourcename_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:JdbcRequest)
  }

  // @@protoc_insertion_point(class_scope:JdbcRequest)
  private static final org.github.omnbmh.samples.grpc.protobuf.JdbcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.github.omnbmh.samples.grpc.protobuf.JdbcRequest();
  }

  public static org.github.omnbmh.samples.grpc.protobuf.JdbcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JdbcRequest>
      PARSER = new com.google.protobuf.AbstractParser<JdbcRequest>() {
    public JdbcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JdbcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JdbcRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JdbcRequest> getParserForType() {
    return PARSER;
  }

  public org.github.omnbmh.samples.grpc.protobuf.JdbcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

