// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdbdata.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface JdbcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JdbcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datasourcename = 1;</code>
   */
  java.lang.String getDatasourcename();
  /**
   * <code>string datasourcename = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatasourcenameBytes();
}
