// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routeguide.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitude = 1;</code>
   */
  int getLatitude();

  /**
   * <code>int32 longitude = 2;</code>
   */
  int getLongitude();
}
