// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routeguide.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  org.github.omnbmh.samples.grpc.protobuf.Point getLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  org.github.omnbmh.samples.grpc.protobuf.PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
