// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routeguide.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  Point getLo();
  /**
   * <code>.routeguide.Point lo = 1;</code>
   */
  PointOrBuilder getLoOrBuilder();

  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  Point getHi();
  /**
   * <code>.routeguide.Point hi = 2;</code>
   */
  PointOrBuilder getHiOrBuilder();
}
