// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: searchdbdata.proto

package org.github.omnbmh.samples.grpc.protobuf;

public final class Searchdbdata {
  private Searchdbdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdbcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdbcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JdbcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JdbcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DruidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DruidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DruidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DruidResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022searchdbdata.proto\"%\n\013JdbcRequest\022\026\n\016d" +
      "atasourcename\030\001 \001(\t\"H\n\014JdbcResponse\022\016\n\006r" +
      "esult\030\001 \001(\t\022\017\n\007exetime\030\002 \001(\t\022\027\n\017serverti" +
      "mestamp\030\003 \001(\t\"&\n\014DruidRequest\022\026\n\016datasou" +
      "rcename\030\001 \001(\t\"I\n\rDruidResponse\022\016\n\006result" +
      "\030\001 \001(\t\022\017\n\007exetime\030\002 \001(\t\022\027\n\017servertimesta" +
      "mp\030\003 \001(\t2{\n\014SearchDbData\0223\n\022searchDbData" +
      "ByJdbc\022\014.JdbcRequest\032\r.JdbcResponse\"\000\0226\n" +
      "\023searchDbDataByDruid\022\r.DruidRequest\032\016.Dr" +
      "uidResponse\"\000B+\n\'org.github.omnbmh.sampl",
      "es.grpc.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JdbcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JdbcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdbcRequest_descriptor,
        new String[] { "Datasourcename", });
    internal_static_JdbcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JdbcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JdbcResponse_descriptor,
        new String[] { "Result", "Exetime", "Servertimestamp", });
    internal_static_DruidRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DruidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DruidRequest_descriptor,
        new String[] { "Datasourcename", });
    internal_static_DruidResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DruidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DruidResponse_descriptor,
        new String[] { "Result", "Exetime", "Servertimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
