// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work_assist.proto

package org.github.omnbmh.samples.grpc.protobuf.work.assist;

public interface TextRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.work.assist.TextRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
