// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg01.proto

package org.github.omnbmh.samples.grpc.protobuf.msg01;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.msg.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
