// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.github.omnbmh.samples.grpc.protobuf.zookeeper.protobuf;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Pong)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
