// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.github.omnbmh.samples.grpc.protobuf.zookeeper.protobuf;

/**
 * Protobuf enum {@code RType}
 */
public enum RType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>pingping = 0;</code>
   */
  pingping(0),
  /**
   * <code>pongpong = 1;</code>
   */
  pongpong(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>pingping = 0;</code>
   */
  public static final int pingping_VALUE = 0;
  /**
   * <code>pongpong = 1;</code>
   */
  public static final int pongpong_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RType valueOf(int value) {
    return forNumber(value);
  }

  public static RType forNumber(int value) {
    switch (value) {
      case 0: return pingping;
      case 1: return pongpong;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RType>() {
          public RType findValueByNumber(int number) {
            return RType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.github.omnbmh.samples.grpc.protobuf.zookeeper.protobuf.Pingpong.getDescriptor().getEnumTypes().get(0);
  }

  private static final RType[] VALUES = values();

  public static RType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:RType)
}

