// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg02.proto

package org.github.omnbmh.samples.grpc.protobuf.msg02;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protobuf.msg.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 2;</code>
   */
  java.lang.String getAge();
  /**
   * <code>string age = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgeBytes();
}
