// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingpong.proto

package org.github.omnbmh.samples.grpc.protobuf.zookeeper.protobuf;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ping)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
