// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysqljdbc.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface JdbcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JdbcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string jdbcurl = 1;</code>
   */
  String getJdbcurl();
  /**
   * <code>optional string jdbcurl = 1;</code>
   */
  com.google.protobuf.ByteString
      getJdbcurlBytes();

  /**
   * <code>optional string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>optional string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string userpassword = 3;</code>
   */
  String getUserpassword();
  /**
   * <code>optional string userpassword = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserpasswordBytes();

  /**
   * <code>optional string driverclassname = 4;</code>
   */
  String getDriverclassname();
  /**
   * <code>optional string driverclassname = 4;</code>
   */
  com.google.protobuf.ByteString
      getDriverclassnameBytes();
}
