// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routeguide.proto

package org.github.omnbmh.samples.grpc.protobuf;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .routeguide.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>optional .routeguide.Point location = 1;</code>
   */
  Point getLocation();
  /**
   * <code>optional .routeguide.Point location = 1;</code>
   */
  PointOrBuilder getLocationOrBuilder();

  /**
   * <code>optional string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
